#
#  Copyright (c) 2020, Colin Robertson (wobblyyyy@gmail.com)
#
#  This file is part of the elibsx project. The elibsx project is licensed
#  under the GNU General Public License V3.
#
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the license is distributed on an "AS IS" BASIS, WITHOUT
#  WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
#  license for the specific language governing permissions and limitations
#  under the License.
#
#  Along with this file, you should have received a license file, containing
#  a copy of the GNU General Public License V3. If you did not receive a copy
#  of that license, you may find one online.
#
#  elibsx GitHub repository:
#  https://github.com/Wobblyyyy/elibsx
#
#  GNU General Public License V3:
#  http://www.gnu.org/licenses/gpl-3.0.en.html
#
#

GENERATED_XML_HEADER = '<?xml version="1.0" ?>'

COMMENT_HEADER = [
    GENERATED_XML_HEADER,
    '',
    '<!--',
    '  ~ This file was generated by the rlibx GUI configuration generator.',
    '  ~',
    '  ~ rlibx is available on GitHub at:',
    '  ~ https://github.com/Wobblyyyy/elibsx',
    '  ~',
    '  ~ You can still feel free to modify this XML file manually, but it\'s',
    '  ~ suggested that XML manipulation is handled through the provided GUI.',
    '  ~',
    '  ~ If you\'re seriously confused about what\'s going on here, you can',
    '  ~ check out the robot configuration documentation available on the',
    '  ~ elibsx/rlibx GitHub repository.',
    '  -->'
]


def build_strings(string_list):
    finished_string = "\n"

    for string_element in string_list:
        finished_string += string_element + '\n'

    return finished_string
