package frc.team4361.config;

public enum Common {
    /*
     * Controller related stuff!
     */

    JOYSTICK_L_A("JOYSTICK_L_A"),
    JOYSTICK_L_B("JOYSTICK_L_B"),
    JOYSTICK_L_C("JOYSTICK_L_C"),
    JOYSTICK_L_D("JOYSTICK_L_D"),

    JOYSTICK_R_A("JOYSTICK_R_A"),
    JOYSTICK_R_B("JOYSTICK_R_B"),
    JOYSTICK_R_C("JOYSTICK_R_C"),
    JOYSTICK_R_D("JOYSTICK_R_D"),

    XBOX_A("XBOX_A"),
    XBOX_B("XBOX_B"),
    XBOX_C("XBOX_C"),
    XBOX_D("XBOX_D"),

    /*
     * Swerve drive specific stuff!
     */

    // Drive motors
    SWERVE_DRIVE_FR("SWERVE_DRIVE_FR"),
    SWERVE_DRIVE_FL("SWERVE_DRIVE_FL"),
    SWERVE_DRIVE_BR("SWERVE_DRIVE_BR"),
    SWERVE_DRIVE_BL("SWERVE_DRIVE_BL"),

    // Turn motors
    SWERVE_TURN_FR("SWERVE_TURN_FR"),
    SWERVE_TURN_FL("SWERVE_TURN_FL"),
    SWERVE_TURN_BR("SWERVE_TURN_BR"),
    SWERVE_TURN_BL("SWERVE_TURN_BL"),

    // Drive encoders
    SWERVE_ENCODER_DRIVE_FR_A("SWERVE_ENCODER_DRIVE_FR_A"),
    SWERVE_ENCODER_DRIVE_FR_B("SWERVE_ENCODER_DRIVE_FR_B"),
    SWERVE_ENCODER_DRIVE_FL_A("SWERVE_ENCODER_DRIVE_FL_A"),
    SWERVE_ENCODER_DRIVE_FL_B("SWERVE_ENCODER_DRIVE_FL_B"),
    SWERVE_ENCODER_DRIVE_BR_A("SWERVE_ENCODER_DRIVE_BR_A"),
    SWERVE_ENCODER_DRIVE_BR_B("SWERVE_ENCODER_DRIVE_BR_B"),
    SWERVE_ENCODER_DRIVE_BL_A("SWERVE_ENCODER_DRIVE_BL_A"),
    SWERVE_ENCODER_DRIVE_BL_B("SWERVE_ENCODER_DRIVE_BL_B"),

    // Turn encoders
    SWERVE_ENCODER_TURN_FR_A("SWERVE_ENCODER_TURN_FR_A"),
    SWERVE_ENCODER_TURN_FR_B("SWERVE_ENCODER_TURN_FR_B"),
    SWERVE_ENCODER_TURN_FL_A("SWERVE_ENCODER_TURN_FL_A"),
    SWERVE_ENCODER_TURN_FL_B("SWERVE_ENCODER_TURN_FL_B"),
    SWERVE_ENCODER_TURN_BR_A("SWERVE_ENCODER_TURN_BR_A"),
    SWERVE_ENCODER_TURN_BR_B("SWERVE_ENCODER_TURN_BR_B"),
    SWERVE_ENCODER_TURN_BL_A("SWERVE_ENCODER_TURN_BL_A"),
    SWERVE_ENCODER_TURN_BL_B("SWERVE_ENCODER_TURN_BL_B"),

    // Random
    SWERVE_DIAMETER_FR("SWERVE_DIAMETER_FR"),
    SWERVE_DIAMETER_FL("SWERVE_DIAMETER_FL"),
    SWERVE_DIAMETER_BR("SWERVE_DIAMETER_BR"),
    SWERVE_DIAMETER_BL("SWERVE_DIAMETER_BL"),
    SWERVE_L_A("SWERVE_L_A"),
    SWERVE_L_B("SWERVE_L_B"),
    SWERVE_W_A("SWERVE_W_A"),
    SWERVE_W_B("SWERVE_W_B"),

    /*
     * 2020 SEASON-SPECIFIC NAMES!
     * For a season I wasn't even a part of.
     */

    /*
     * 2021 SEASON-SPECIFIC NAMES!
     * For a season I may have been a part of. Possibly.
     */

    // Intake
    INTAKE_ROLLER_MOTOR("INTAKE_ROLLER_MOTOR"),
    INTAKE_ACTUATION_MOTOR("INTAKE_ACTUATION_MOTOR"),
    INTAKE_TOP_LIMIT("INTAKE_TOP_LIMIT"),
    INTAKE_BOTTOM_LIMIT("INTAKE_BOTTOM_LIMIT"),

    // Shooter - Flywheel
    SHOOTER_MOTOR_FLYWHEEL("SHOOTER_MOTOR_FLYWHEEL"),
    SHOOTER_ENCODER_FLYWHEEL_A("SHOOTER_ENCODER_FLYWHEEL_A"),
    SHOOTER_ENCODER_FLYWHEEL_B("SHOOTER_ENCODER_FLYWHEEL_B"),
    SHOOTER_TPR_FLYWHEEL("SHOOTER_TPR_FLYWHEEL"),
    SHOOTER_DIAMETER_FLYWHEEL("SHOOTER_DIAMETER_FLYWHEEL"),

    // Shooter - Actuator
    SHOOTER_MOTOR_ACTUATOR("SHOOTER_MOTOR_ACTUATOR"),
    SHOOTER_ENCODER_ACTUATOR_A("SHOOTER_ENCODER_ACTUATOR_A"),
    SHOOTER_ENCODER_ACTUATOR_B("SHOOTER_ENCODER_ACTUATOR_B"),
    SHOOTER_TPR_ACTUATOR("SHOOTER_TPR_ACTUATOR"),
    SHOOTER_DIAMETER_ACTUATOR("SHOOTER_DIAMETER_ACTUATOR"),

    // Storage
    STORAGE_MOTOR("STORAGE_MOTOR"),
    STORAGE_ENCODER("STORAGE_ENCODER"),

    /*
     * SUBSYSTEMS!
     * Because you can't ever have enough subsystems.
     */

    // Swerve subsystems
    SUB_SWERVE_A("SUB_SWERVE_A"),
    SUB_SWERVE_B("SUB_SWERVE_B"),
    SUB_SWERVE_C("SUB_SWERVE_C"),
    SUB_SWERVE_D("SUB_SWERVE_D"),

    // Tank subsystems
    SUB_TANK_A("SUB_TANK_A"),
    SUB_TANK_B("SUB_TANK_B"),
    SUB_TANK_C("SUB_TANK_C"),
    SUB_TANK_D("SUB_TANK_D"),

    // Meccanum subsystems
    SUB_MECCANUM_A("SUB_MECCANUM_A"),
    SUB_MECCANUM_B("SUB_MECCANUM_B"),
    SUB_MECCANUM_C("SUB_MECCANUM_C"),
    SUB_MECCANUM_D("SUB_MECCANUM_D"),

    // Intake subsystems
    SUB_INTAKE_A("SUB_INTAKE_A"),
    SUB_INTAKE_B("SUB_INTAKE_B"),
    SUB_INTAKE_C("SUB_INTAKE_C"),
    SUB_INTAKE_D("SUB_INTAKE_D"),

    // Climber subsystems
    SUB_CLIMBER_A("SUB_CLIMBER_A"),
    SUB_CLIMBER_B("SUB_CLIMBER_B"),
    SUB_CLIMBER_C("SUB_CLIMBER_C"),
    SUB_CLIMBER_D("SUB_CLIMBER_D"),

    // Gripper subsystems
    SUB_GRIPPER_A("SUB_GRIPPER_A"),
    SUB_GRIPPER_B("SUB_GRIPPER_B"),
    SUB_GRIPPER_C("SUB_GRIPPER_C"),
    SUB_GRIPPER_D("SUB_GRIPPER_D"),

    // Conveyor subsystems
    SUB_CONVEYOR_A("SUB_CONVEYOR_A"),
    SUB_CONVEYOR_B("SUB_CONVEYOR_B"),
    SUB_CONVEYOR_C("SUB_CONVEYOR_C"),
    SUB_CONVEYOR_D("SUB_CONVEYOR_D"),

    // Shooter subsystems
    SUB_SHOOTER_A("SUB_SHOOTER_A"),
    SUB_SHOOTER_B("SUB_SHOOTER_B"),
    SUB_SHOOTER_C("SUB_SHOOTER_C"),
    SUB_SHOOTER_D("SUB_SHOOTER_D"),

    // Storage subsystems
    SUB_STORAGE_A("SUB_STORAGE_A"),
    SUB_STORAGE_B("SUB_STORAGE_B"),
    SUB_STORAGE_C("SUB_STORAGE_C"),
    SUB_STORAGE_D("SUB_STORAGE_D"),

    /*
     * RANDOM VARIABLES!
     * Because who doesn't love those, right?
     */

    // CPR
    SWERVE_CPR_A("SWERVE_CPR_A"),
    SWERVE_CPR_B("SWERVE_CPR_B"),
    SWERVE_CPR_C("SWERVE_CPR_C"),
    SWERVE_CPR_D("SWERVE_CPR_D"),

    /*
     * MOTORS!
     * Mostly motors used for driving, actually.
     */

    // Four wheel drive
    DRIVE_FR("DRIVE_FR"),
    DRIVE_FL("DRIVE_FL"),
    DRIVE_BR("DRIVE_BR"),
    DRIVE_BL("DRIVE_BL"),

    // Swerve drive
    DRIVE_FRD("SWERVE_FRD"),
    DRIVE_FRT("SWERVE_FRT"),
    DRIVE_FLD("SWERVE_FLD"),
    DRIVE_FLT("SWERVE_FLT"),
    DRIVE_BRD("SWERVE_BRD"),
    DRIVE_BRT("SWERVE_BRT"),
    DRIVE_BLD("SWERVE_BLD"),
    DRIVE_BLT("SWERVE_BLT"),

    /*
     * MOTORS!
     * Mostly motors not used for driving, actually.
     */

    // Intake motors
    MOTOR_INTAKE_A("INTAKE_A"),
    MOTOR_INTAKE_B("INTAKE_B"),
    MOTOR_INTAKE_C("INTAKE_C"),
    MOTOR_INTAKE_D("INTAKE_D"),

    // Climber motors
    MOTOR_CLIMBER_A("CLIMBER_A"),
    MOTOR_CLIMBER_B("CLIMBER_B"),
    MOTOR_CLIMBER_C("CLIMBER_C"),
    MOTOR_CLIMBER_D("CLIMBER_D"),

    // Shooter motors
    MOTOR_SHOOTER_A("SHOOTER_A"),
    MOTOR_SHOOTER_B("SHOOTER_B"),
    MOTOR_SHOOTER_C("SHOOTER_C"),
    MOTOR_SHOOTER_D("SHOOTER_D"),

    // Gripper motors
    MOTOR_GRIPPER_A("GRIPPER_A"),
    MOTOR_GRIPPER_B("GRIPPER_B"),
    MOTOR_GRIPPER_C("GRIPPER_C"),
    MOTOR_GRIPPER_D("GRIPPER_D"),

    // Conveyor motors
    MOTOR_CONVEYOR_A("CONVEYOR_A"),
    MOTOR_CONVEYOR_B("CONVEYOR_B"),
    MOTOR_CONVEYOR_C("CONVEYOR_C"),
    MOTOR_CONVEYOR_D("CONVEYOR_D"),

    // Generic motors. Not assigned to any particular subsystem.
    MOTOR_A("MOTOR_A"), // 1
    MOTOR_B("MOTOR_B"), // 2
    MOTOR_C("MOTOR_C"), // 3
    MOTOR_D("MOTOR_D"), // 4
    MOTOR_E("MOTOR_E"), // 5
    MOTOR_F("MOTOR_F"), // 6
    MOTOR_G("MOTOR_G"), // 7
    MOTOR_H("MOTOR_H"), // 8

    /*
     * ENCODERS!
     * Encoders used for encoding things.
     */

    // Three-wheel odometry
    ODOMETRY_RIGHT("ODOMETRY_RIGHT"),
    ODOMETRY_LEFT("ODOMETRY_LEFT"),
    ODOMETRY_MID("ODOMETRY_FRONT_BACK"),

    // Swerve drive
    ENCODER_SWERVE_FR("ENCODER_SWERVE_FR"),
    ENCODER_SWERVE_FL("ENCODER_SWERVE_FL"),
    ENCODER_SWERVE_BR("ENCODER_SWERVE_BR"),
    ENCODER_SWERVE_BL("ENCODER_SWERVE_BL"),

    // Intake / shooter / climber / gripper encoders
    ENCODER_INTAKE_A("ENCODER_INTAKE_A"),
    ENCODER_INTAKE_B("ENCODER_INTAKE_B"),
    ENCODER_SHOOTER_A("ENCODER_SHOOTER_A"),
    ENCODER_SHOOTER_B("ENCODER_SHOOTER_B"),
    ENCODER_CLIMBER_A("ENCODER_CLIMBER_A"),
    ENCODER_CLIMBER_B("ENCODER_CLIMBER_B"),
    ENCODER_GRIPPER_A("ENCODER_GRIPPER_A"),
    ENCODER_GRIPPER_B("ENCODER_GRIPPER_B"),

    // Generic encoders. Not assigned to any particular subsystem.
    ENCODER_A("ENCODER_A"), // 1
    ENCODER_B("ENCODER_B"), // 2
    ENCODER_C("ENCODER_C"), // 3
    ENCODER_D("ENCODER_D"), // 4
    ENCODER_E("ENCODER_E"), // 5
    ENCODER_F("ENCODER_F"), // 6
    ENCODER_G("ENCODER_G"), // 7
    ENCODER_H("ENCODER_H"), // 8

    /*
     * SUBSYSTEMS!
     * Very cool, I know.
     */

    // Swerve
    DRIVETRAIN_SWERVE_A("DRIVETRAIN_SWERVE_A"),
    DRIVETRAIN_SWERVE_B("DRIVETRAIN_SWERVE_B"),
    DRIVETRAIN_SWERVE_C("DRIVETRAIN_SWERVE_C"),
    DRIVETRAIN_SWERVE_D("DRIVETRAIN_SWERVE_D"),

    // Meccanum
    DRIVETRAIN_MECCANUM_A("DRIVETRAIN_MECCANUM_A"),
    DRIVETRAIN_MECCANUM_B("DRIVETRAIN_MECCANUM_B"),
    DRIVETRAIN_MECCANUM_C("DRIVETRAIN_MECCANUM_C"),
    DRIVETRAIN_MECCANUM_D("DRIVETRAIN_MECCANUM_D"),

    // TANK
    DRIVETRAIN_TANK_A("DRIVETRAIN_TANK_A"),
    DRIVETRAIN_TANK_B("DRIVETRAIN_TANK_B"),
    DRIVETRAIN_TANK_C("DRIVETRAIN_TANK_C"),
    DRIVETRAIN_TANK_D("DRIVETRAIN_TANK_D");

    private String name;

    Common(String name) {
        this.name = name;
    }

    public String getName() {
        return name;
    }
}
